import { useEffect, useState } from "react";
import { api } from "../api/client";
import { useLanguage } from "../i18n";
import { getToken } from "../api/session";
import { useNavigate } from "react-router-dom";

type AdminUser={id:string;email:string;displayName:string;isHost:boolean;isAdmin:boolean;isBlocked:boolean};
type HostApplication={id:string;fullName:string;documentUrl:string;status:number;adminNote:string|null;createdAtUtc:string;applicantName:string|null;applicantEmail:string|null};
export function AdminPage(){const{t}=useLanguage();const nav=useNavigate();const[users,setUsers]=useState<AdminUser[]>([]);const[apps,setApps]=useState<HostApplication[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const [u,a]=await Promise.all([api<AdminUser[]>("/api/admin/users"),api<HostApplication[]>("/api/admin/host-applications")]);setUsers(u);setApps(a)}catch(e){const m=e instanceof Error?e.message:"";setError(m);if(!getToken())nav("/login")}finally{setLoading(false)}}
 useEffect(()=>{load()},[nav]);
 async function action(path:string){try{await api(path,{method:"POST",body:path.includes("reject")?JSON.stringify({note:"Rejected by administrator"}):undefined});await load()}catch(e){setError(e instanceof Error?e.message:"Error")}}
 return <section><h1>{t("adminTitle")}</h1>{loading&&<p>{t("loading")}</p>}{error&&<p className="error">{error}</p>}<div className="admin-grid"><div className="profile-card"><h2>{t("hostApplications")}</h2>{apps.length===0?<p>{t("noApplications")}</p>:<ul className="bookings-list">{apps.map(a=><li className="booking-row" key={a.id}><div><strong>{a.fullName}</strong><p>{a.applicantEmail??""} · {new Date(a.createdAtUtc).toLocaleDateString()}</p><a href={a.documentUrl} target="_blank" rel="noreferrer">{t("openDocument")}</a><p>{a.status===0?t("applicationPending"):a.status===1?t("applicationApproved"):t("applicationRejected")}</p></div>{a.status===0&&<div className="button-row"><button className="auth-primary" onClick={()=>action(`/api/admin/host-applications/${a.id}/approve`)}>{t("approve")}</button><button className="text-btn" onClick={()=>action(`/api/admin/host-applications/${a.id}/reject`)}>{t("reject")}</button></div>}</li>)}</ul>}</div><div className="profile-card"><h2>{t("users")}</h2><ul className="bookings-list">{users.map(u=><li className="booking-row" key={u.id}><div><strong>{u.displayName}</strong><p>{u.email}</p><p>{u.isAdmin?t("administrator"):u.isHost?t("hostRole"):t("guestRole")} · {u.isBlocked?t("blocked"):t("active")}</p></div>{!u.isAdmin&&<button className="text-btn" onClick={()=>action(`/api/admin/users/${u.id}/${u.isBlocked?"unblock":"block"}`)}>{u.isBlocked?t("unblock"):t("block")}</button>}</li>)}</ul></div></div></section>}
