import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api, type AuthResponse } from "../api/client";
import { setSession } from "../api/session";
import { BrandIcon } from "../components/BrandIcon";
import { useLanguage } from "../i18n";
type Mode="login"|"register"; type Providers={google:boolean};
const apiOrigin=import.meta.env.DEV?(import.meta.env.VITE_API_ORIGIN||"http://localhost:5176"):"";
export function AuthPage({mode}:{mode:Mode}){const {t}=useLanguage();const navigate=useNavigate();const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirmPassword,setConfirmPassword]=useState("");const[displayName,setDisplayName]=useState("");const[error,setError]=useState<string|null>(null);const[providers,setProviders]=useState<Providers>({google:false});useEffect(()=>{api<Providers>("/api/auth/providers").then(setProviders).catch(()=>undefined)},[]);async function onSubmit(event:FormEvent){event.preventDefault();setError(null);if(mode==="register"&&password!==confirmPassword){setError(t("passwordsMismatch"));return}try{const path=mode==="login"?"/api/auth/login":"/api/auth/register";const body=mode==="login"?{email,password}:{email,password,confirmPassword,displayName};const result=await api<AuthResponse>(path,{method:"POST",body:JSON.stringify(body)});setSession(result.accessToken);navigate("/",{replace:true})}catch(e){setError(e instanceof Error?e.message:t("error"))}}function startGoogle(){const base=apiOrigin.replace(/\/$/,"");window.location.assign(`${base}/api/auth/external/google`)}return <div className="auth-overlay"><form className="auth-card" onSubmit={onSubmit}><h1>{mode==="login"?t("loginTitle"):t("registerTitle")}</h1><p className="auth-lead">{mode==="login"?t("loginLead"):t("registerLead")}</p><div className="social-stack"><button type="button" className="social-btn" onClick={startGoogle}><span className="social-label"><BrandIcon name="Google" />{t("continueGoogle")}</span>{!providers.google&&<span className="social-hint">{t("keysNeeded")}</span>}</button></div><p className="auth-or">{t("or")}</p>{mode==="register"&&<label>{t("name")}<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>{t("password")}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6}/></label>{mode==="register"&&<label>{t("confirmPassword")}<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required minLength={6}/></label>}{error&&<p className="error">{error}</p>}<button type="submit" className="auth-primary">{mode==="login"?t("login"):t("createAccount")}</button><p className="auth-switch">{mode==="login"?<>{t("noAccount")} <Link to="/register">{t("signup")}</Link></>:<>{t("alreadyAccount")} <Link to="/login">{t("login")}</Link></>}</p></form></div>}
