import { FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, mediaUrl, type ListingCard, type ListingSearchResult } from "../api/client";
import { CategoryPicker } from "../components/CategoryPicker";
import { useLanguage } from "../i18n";

type Filters = { q:string; city:string; guests:string; minPrice:string; maxPrice:string; categories:number[]; checkIn:string; checkOut:string };
const emptyFilters: Filters = { q:"", city:"", guests:"", minPrice:"", maxPrice:"", categories:[], checkIn:"", checkOut:"" };

export function HomePage(){
 const {t}=useLanguage(); const [listings,setListings]=useState<ListingCard[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(25); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [filters,setFilters]=useState<Filters>(emptyFilters); const [openFilters,setOpenFilters]=useState(false);
 function load(nextPage=page,nextSize=pageSize,nextFilters=filters){const params=new URLSearchParams(); if(nextFilters.q.trim())params.set("q",nextFilters.q.trim()); if(nextFilters.city.trim())params.set("city",nextFilters.city.trim()); if(nextFilters.guests)params.set("guests",nextFilters.guests); if(nextFilters.minPrice)params.set("minPrice",nextFilters.minPrice); if(nextFilters.maxPrice)params.set("maxPrice",nextFilters.maxPrice); if(nextFilters.checkIn&&nextFilters.checkOut){params.set("checkIn",nextFilters.checkIn);params.set("checkOut",nextFilters.checkOut)} nextFilters.categories.forEach(c=>params.append("categories",String(c))); params.set("page",String(nextPage));params.set("pageSize",String(nextSize));setLoading(true);api<ListingSearchResult>(`/api/listings?${params}`).then(r=>{setListings(r.items);setTotal(r.total);setPage(r.page);setPageSize(r.pageSize)}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false));}
 useEffect(()=>{load(1,pageSize,filters)},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const setFilter=<K extends keyof Filters>(key:K,value:Filters[K])=>setFilters(c=>({...c,[key]:value}));
 const activeFilters=Number(Boolean(filters.q.trim()))+Number(Boolean(filters.city.trim()))+Number(Boolean(filters.guests))+Number(Boolean(filters.minPrice||filters.maxPrice))+Number(filters.categories.length>0)+Number(Boolean(filters.checkIn&&filters.checkOut));
 const pageCount=Math.max(1,Math.ceil(total/pageSize));
 return <section className="home"><h1>{t("homeTitle")}</h1><form className="search-bar" onSubmit={(e:FormEvent)=>{e.preventDefault();setError(null);setOpenFilters(false);load(1,pageSize,filters)}}><label className="title-search">{t("search")}<input value={filters.q} onChange={e=>setFilter("q",e.target.value)} placeholder={t("titleWords")}/></label><button type="button" className="dropdown-toggle" onClick={()=>setOpenFilters(v=>!v)}>{activeFilters>0?`${t("filter")} (${activeFilters})`:t("filter")}</button><button type="submit" className="auth-primary">{t("search")}</button></form>
 {openFilters&&<div className="filter-panel"><label>{t("titleWords")}<input value={filters.q} onChange={e=>setFilter("q",e.target.value)} placeholder={t("titlePlaceholder")}/></label><label>{t("city")}<input value={filters.city} onChange={e=>setFilter("city",e.target.value)} placeholder={t("cityPlaceholder")}/></label><label>{t("guests")}<input type="number" min={1} value={filters.guests} onChange={e=>setFilter("guests",e.target.value)}/></label><label>{t("minPrice")}<input type="number" min={0} value={filters.minPrice} onChange={e=>setFilter("minPrice",e.target.value)}/></label><label>{t("maxPrice")}<input type="number" min={0} value={filters.maxPrice} onChange={e=>setFilter("maxPrice",e.target.value)}/></label><label>{t("checkIn")}<input type="date" value={filters.checkIn} onChange={e=>setFilter("checkIn",e.target.value)}/></label><label>{t("checkOut")}<input type="date" value={filters.checkOut} onChange={e=>setFilter("checkOut",e.target.value)}/></label><CategoryPicker values={filters.categories} onChange={values=>setFilter("categories",values)}/><div className="filter-actions"><button type="button" className="text-btn" onClick={()=>setFilters(emptyFilters)}>{t("reset")}</button><button type="button" className="auth-primary" onClick={()=>{setOpenFilters(false);load(1,pageSize,filters)}}>{t("apply")}</button></div></div>}
 {error&&<p className="error">{error}</p>}<div className="pager"><span>{total} {t("listings")}</span><label>{t("perPage")}<select value={pageSize} onChange={e=>{const size=Number(e.target.value);setPageSize(size);load(1,size,filters)}}><option>25</option><option>50</option><option>100</option></select></label></div>
 <div className="listing-grid">{listings.map(l=><Link key={l.id} to={`/listings/${l.id}`} className="listing-card">{l.coverPhotoUrl?<img className="listing-photo" src={mediaUrl(l.coverPhotoUrl)} alt=""/>:<div className="listing-photo"/>}<h2>{l.title}</h2><p>{l.city}, {l.region}</p><p>${l.pricePerNight} / {t("night")}{l.reviewCount>0?` · ${l.rating.toFixed(2)} (${l.reviewCount} ${t("reviews")})`:""}</p></Link>)}</div>
 {listings.length===0&&!error&&!loading&&<p>{t("nothingFound")}</p>}{pageCount>1&&<div className="pager"><button type="button" className="dropdown-toggle" disabled={page<=1} onClick={()=>load(page-1,pageSize,filters)}>{t("previous")}</button><span>{t("page")} {page} / {pageCount}</span><button type="button" className="dropdown-toggle" disabled={page>=pageCount} onClick={()=>load(page+1,pageSize,filters)}>{t("next")}</button></div>}</section>;
}
